---
- name: Create a cron job
  ansible.builtin.cron:
    name: "{{ cron_name }}"
    job: "{{ cron_job_cmd }}"
    user: "{{ cron_user }}"
    minute: "{{ minute }}"
    hour: "{{ hour }}"
  when: action == "add"

  tags: [ add_cron ]

- name: Create a cron file under /etc/cron.d
  ansible.builtin.cron:
    name: "{{ cron_name }}"
    weekday: "2"
    minute: "0"
    hour: "12"
    user: "{{ cron_user }}"
    job: "{{ cron_job_cmd }}"
    cron_file: "{{ cron_job_file }}"
  when: action == "addfile"

  tags: [ add_crond ]

- name: Update a cron job
  ansible.builtin.cron:
    name: "{{ cron_name }}"
    job:  "{{ cron_job_cmd }}"
    user: "{{ cron_user }}"
    minute: "{{ minute }}"
    hour: "{{ hour }}"
  when: action == "update"

  tags: [ update_cron ]

- name: Remove a cron job
  ansible.builtin.cron:
    name: "{{ cron_name }}"
    user: "{{ cron_user }}"
    state:  absent
  when: action == "remove"

  tags: [ remove_cron ]
